baseURL = "https://example.com/"
languageCode = "en-us"
title = "My Awesome Blog"
theme = "terminal"

[params]
  subtitle = "Welcome to my Hugo blog"
  [[params.social]]
    name = "github"
    url = "https://github.com/yourusername"

